### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by rotatingJazz** [yapplabs/ember-key-responder#17]
Just did a fresh install of ember-cli 0.2.5 and ember-cli-materialize.

I get a few warnings like this:
````
DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookupFactory (http://127.0.0.1:4200/assets/vendor.js:11042:26)
        at Object.initialize (http://127.0.0.1:4200/assets/myapp.js:737:17)
        at http://127.0.0.1:4200/assets/vendor.js:13521:23
        at http://127.0.0.1:4200/assets/vendor.js:13544:9
        at visit (http://127.0.0.1:4200/assets/vendor.js:11560:7)
        at DAG.topsort (http://127.0.0.1:4200/assets/vendor.js:11672:11)
        at Namespace.default.extend._runInitializer (http://127.0.0.1:4200/assets/vendor.js:13543:13)
        at Namespace.default.extend.runInitializers (http://127.0.0.1:4200/assets/vendor.js:13517:12)
        at Namespace.default.extend.boot (http://127.0.0.1:4200/assets/vendor.js:13433:12)
````

This one was from `ember-key-responder`: https://github.com/yapplabs/ember-key-responder/blob/master/app/initializers/key-responder.js. The container lookups need to be refactored to the upcoming new standard.

**Comment by mayatron** [comment]
+1

**Comment by alvinvogelzang** [comment]
+1

**Comment by wolfbiter** [comment]
+1

**Comment by acorncom** [comment]
@lukemelia I may be able to send in a pull request for this, if you have some guidance on how you want to handle backwards compatibility?

**Comment by lukemelia** [comment]
@acorncom I would like to support 1.11, 1.12, and 1.13. Let me know what the sticking points are and I can help brainstorm a solution

**Comment by acorncom** [comment]
@lukemelia The api changes for initializers (http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers) in Ember 1.11.  So if we're ok with shifting to only supporting the new format, theoretically we should be ok.  Haven't tried it yet though ;-)

**Comment by mike-north** [comment]
Perhaps https://github.com/yapplabs/ember-key-responder/pull/15 means we can close this
